### ISSUE TITLE
Thank you Page error

### ISSUE THREAD

**Issue by stefanliden** [Billmate/magento-2-billmate-checkout#84]
Billmate merchant (Magento:2.4.0)  has done a little more testing on our version 1.7.0. However, it seems that they sporadically get this error instead when they place an order and are redirected to the order confirmation page:

```

[2020-09-28 09:49:45] main.INFO: Initialize execute in Success [] []
[2020-09-28 09:49:45] main.INFO: Inside the try statement [] []
[2020-09-28 09:49:45] main.INFO: Inside values [] []
[2020-09-28 09:49:45] main.INFO: Inside paymentinfo [] []
[2020-09-28 09:49:45] main.INFO: No session data exist [] []
[2020-09-28 09:49:45] main.CRITICAL: TypeError: Argument 1 passed to Magento\Framework\DataObject::addData() must be of the type array, null given, called in /var/www/html/vendor/billmate/magento2-checkout/Model/Order.php on li$
Stack trace:
#0 /var/www/html/vendor/billmate/magento2-checkout/Model/Order.php(180): Magento\Framework\DataObject->addData(NULL)
#1 /var/www/html/vendor/billmate/magento2-checkout/Model/Order.php(232): Billmate\BillmateCheckout\Model\Order->createQuote(NULL, Object(Magento\Customer\Model\Data\Customer))
#2 /var/www/html/vendor/billmate/magento2-checkout/Model/Order.php(114): Billmate\BillmateCheckout\Model\Order->createCart(NULL)
#3 /var/www/html/vendor/billmate/magento2-checkout/Controller/Success/Success.php(144): Billmate\BillmateCheckout\Model\Order->create()
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Billmate\BillmateCheckout\Controller\Success\Success->execute()
#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->___callParent('execute', Array)
#6 /var/www/html/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->Magento\Framework\Interception{closure}()
#7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Billmate\BillmateCheckout\Controller\Success\Success\Interceptor)$
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->Magento\Framework\Interception{closure}()
#9 /var/www/html/generated/code/Billmate/BillmateCheckout/Controller/Success/Success/Interceptor.php(26): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->___callPlugins('execute', Array, Array)
#10 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->execute()
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->___callParent('dispatch', Array)
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/generated/code/Billmate/BillmateCheckout/Controller/Success/Success/Interceptor.php(39): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->___callPlugins('dispatch', Array, Array)
#15 /var/www/html/vendor/magento/framework/App/FrontController.php(186): Billmate\BillmateCheckout\Controller\Success\Success\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Billmate\BillmateCheckout\Controller\Success\Succ$
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Requ$
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closur$
#21 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Reques$
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure),$
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#25 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#27 /var/www/html/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))


```

**Comment by MaxMalmer** [comment]
Hey,
This is an issue that was hidden by the fact that orders were placed broken before and errors ignored.
The problem is due to a faulty NULL check. We're looking at it now.

**Comment by MaxMalmer** [comment]
This is issue is now handled. It happens when a customers session is over, this setting can be controlled by the Billmate customer in Magento 2. It's set to 1 hour by default. It can also be set in php.ini for the server.
